# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: 'mem'
    ports:
    - "5432:5432"
    
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "haldey" 


  


